### ISSUE TITLE
Unexpected (nil, nil) result from wincred.GetGenericCredential

### ISSUE THREAD

**Issue by frazeradam** [danieljoos/wincred#32] opened 2022-09-13 21:57 UTC
Let me start off by saying that I don't think this is a bug in the package, but I'm hoping you might have an idea on why I'm getting both a nil credential and a nil error coming back.  I've traced it to unexpected results in `sysCredRead` where the wrapped system call is returning 1 (indicating success), yet pcred remains nil.  Unsurprisingly this unexpected output causes invalid output up the chain of calls and panics if a nil error is presumed to mean the credential pointer is valid.  The only at all atypical thing I'm doing is calling it from within CGo, but I can't see any reason why that should make a difference.

**Comment by danieljoos** [comment] 2022-10-13 09:15
Sorry for the late response.

That issue sounds interesting. I could imagine some out-of-memory issues. Can you reproduce that behaviour reliably on your end? Is there anything interesting returned from `GetLastError()` when called after `CredRead`?

**Comment by mislav** [comment] 2023-04-07 13:09
I have successfully reproduced this in GitHub CLI based on a user report https://github.com/cli/cli/issues/7283, but have been pulling my hair for one whole day while trying to come up with an isolated reproduction case for this. As soon as I touched anything about the (large) program that reproduces this, GetGenericCredential would start working again as designed. Sprinkling in some debug statements revealed that the failure occurs for _some_ pointer values of pcred but not for others: https://github.com/danieljoos/wincred/blob/90f7265cb767c0e62a5b43a96e232ca7f41a7d44/sys.go#L68

If my hunch is true, then this is a memory issue and is dependent on the current memory allocation state of the program at the time that the syscall runs. When reading the Windows API documentation on CredReadW, I wasn't really clear on whether it expects us to pre-allocate a struct in memory, so I've tried that and it seemed to work. I've sent a PR that illustrates my workaround, but please take it with a grain of salt.

**Comment by mislav** [comment] 2023-04-19 12:43
@danieljoos I've been able to reproduce this on both Windows 10 and Windows 11.

To most reliably reproduce, you can try compiling `cli/cli` from source (via `script\build`) and running `bin\gh.exe release --repo cli/cli view v2.26.0`.

Things I have tried that did not have any effect:
- Use `runtime.KeepAlive` for variables passed to syscalls during `sysCredRead()`
- Add `//go:uintptrescapes` compiler directive to `sysCredRead()` - this is likely a no-op since the implementation of `Proc.Call` already contains that directive
- Adding a mutex around `sysCredRead` to ensure that they do not happen concurrently
- Upgrading the `sys` dependency to latest version

Something interesting I have noticed: a some prominent callers of `wincred.GetGenericCredentials` actually handle cases when both return values were nil, indicating that they might have stumbled on this problem before and worked around it:
- https://github.com/docker/docker-credential-helpers/blob/da93839996460f358368e183cbd8da06feae3fec/wincred/wincred_windows.go#L49-L51
- https://github.com/keys-pub/keys/blob/4283a10cbf488abf47195268cdc3721883ed8119/keyring/keyring_windows.go#L32-L40

The internal function that does conversion from Windows to Go struct also has a guard that returns nil early if `pcred` is nil:
https://github.com/danieljoos/wincred/blob/90f7265cb767c0e62a5b43a96e232ca7f41a7d44/conversion.go#L48-L51

**Comment by danieljoos** [comment] 2023-05-02 16:42
@mislav Thank you for the details. I was able to reproduce it following your instructions.

I really don't know what's happening here.
The `CreadReadW` syscall doesn't set the output object - the given pointer remains `nil`.

For your particular example, this **always** happens for the `published release lookup` and **never** for the `draft release lookup`. Running both without go-routines in sequence, causes everything to work just fine.

What I investigated so far:
- Created an example project with hundreds of goroutines reading a single credential in parallel. Worked without issues.
- Debugged the OS threads these goroutines do run in: Both different from the main thread, one of them works, the other not. So there's no strict need for this to run on the main thread (I remember some windows functions need this).
- Tried to lock the OS thread to the given goroutines - no difference
- Tried to lock access to the cred-read function via mutex - no difference
- Investigated on the context cancelling below both goroutines (in `cli/cli`) - that point of the code isn't even reached.

There seems to be something that the `publish release lookup` (in `cli/cli`) does, which causes problems with the cred-read. Then again, when run in sequence without goroutines, everything works just fine.

**Comment by danieljoos** [comment] 2023-05-06 12:33
I traced the calls to `CredReadW` using `API Monitor` and `Process Monitor`. 
It shows that the actual call to the DLL function sets the pointer value to a non-NULL value.
I'll continue to look into the issue and see if I can find out why the pointer on the Go-side of things is still `nil`.

**Comment by danieljoos** [comment] 2023-05-06 14:48
I'm pretty sure to have found the issue. It is discussed here:
https://github.com/golang/go/issues/34684

Moving away from `LazyProc` seems to solve the issue. I'm still trying to play around with it a bit and see if I can come up with a PR soon.

**Comment by mislav** [comment] 2023-05-08 10:16
@danieljoos Thanks so much for diving into this.

I was also looking at that Go issue, but it seemed that since that issue was opened, [changes landed to Go](https://go-review.googlesource.com/c/go/+/198043) that made it "safer" to use `LazyProc.Call`. However, since the issue is still open, maybe there are still some problems with pointer conversions there, but I must admit I don't understand the root of the problem.

If switching to SyscallN addresses the issue, that would be very welcome.

**Comment by chkohner** [comment] 2023-05-08 19:56
We've started hitting this as well. Looking forward to your PR.

**Comment by danieljoos** [comment] 2023-05-14 18:46
Please have a look at the changes if you like:
https://github.com/danieljoos/wincred/pull/42

**Comment by danieljoos** [comment] 2023-05-16 09:50
Closing this for the moment. Issue is hopefully resolved in version `v1.2.0`.
Please feel free to reopen the issue if you still see it happening.

**Closed by danieljoos** 2023-05-16 09:50 UTC
