### ISSUE TITLE
Fails for non-english locales

### ISSUE THREAD

**Issue by gabriel** [danieljoos/wincred#15] opened 2020-05-11 01:13 UTC
For example, in Windows 10 French:

```
$ go test
go: finding module for package github.com/stretchr/testify/assert
go: finding module for package github.com/stretchr/testify/mock
go: downloading github.com/stretchr/testify v1.5.1
go: found github.com/stretchr/testify/assert in github.com/stretchr/testify v1.5.1
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading github.com/stretchr/objx v0.1.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/pmezard/go-difflib v1.0.0
--- FAIL: TestGenericCredential_EndToEnd (0.01s)
    wincred_test.go:59:
                Error Trace:    wincred_test.go:59
                Error:          Expected nil, but got: 0x490
                Test:           TestGenericCredential_EndToEnd
    wincred_test.go:60:
                Error Trace:    wincred_test.go:60
                Error:          Expected value not to be nil.
                Test:           TestGenericCredential_EndToEnd
--- FAIL: TestGetGenericCredential_NotFound (0.00s)
    wincred_test.go:74:
                Error Trace:    wincred_test.go:74
                Error:          Not equal:
                                expected: "Element not found."
                                actual  : "Élément introuvable."

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Element not found.
                                +Élément introuvable.
                Test:           TestGetGenericCredential_NotFound
--- FAIL: TestGetGenericCredential_Empty (0.00s)
    wincred_test.go:83:
                Error Trace:    wincred_test.go:83
                Error:          Not equal:
                                expected: "The parameter is incorrect."
                                actual  : "Paramètre incorrect."

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -The parameter is incorrect.
                                +Paramètre incorrect.
                Test:           TestGetGenericCredential_Empty
--- FAIL: TestGenericCredential_WriteEmpty (0.00s)
    wincred_test.go:92:
                Error Trace:    wincred_test.go:92
                Error:          Not equal:
                                expected: "The parameter is incorrect."
                                actual  : "Paramètre incorrect."

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -The parameter is incorrect.
                                +Paramètre incorrect.
                Test:           TestGenericCredential_WriteEmpty
--- FAIL: TestGenericCredential_DeleteNotFound (0.00s)
    wincred_test.go:101:
                Error Trace:    wincred_test.go:101
                Error:          Not equal:
                                expected: "Element not found."
                                actual  : "Élément introuvable."

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Element not found.
                                +Élément introuvable.
                Test:           TestGenericCredential_DeleteNotFound
FAIL
exit status 1
FAIL    github.com/keys-pub/wincred     0.287s
```

**Comment by gabriel** [comment] 2020-05-11 01:50
The fix for this is here: https://github.com/danieljoos/wincred/pull/16

**Comment by gabriel** [comment] 2020-05-11 17:59
One thing to note, in order to reproduce I had to install the Windows French ISO. (Adding in a French language pack and switching languages did NOT reproduce the issue.)

**Comment by danieljoos** [comment] 2020-05-12 19:51
Thanks for posting this. This is very interesting. I wasn't able to get a windows VM to reproduce this. But all my VMs were installed using the English ISO.

I looked up the code that Go uses to create the error message, and it looks like it forces `en_US` locale for the messages. Maybe when you install using the french ISO, the english locale isn't available at all?
(see https://golang.org/src/syscall/syscall_windows.go - line 126).

I had a look at your PR and found an easier solution to the issue - also without losing backwards compatibility. Could you please try this branch https://github.com/danieljoos/wincred/tree/LocaleErrorHandling and see if it fixes the issue on your system?

**Comment by gabriel** [comment] 2020-05-12 20:35
Yeah that branch works.

You'd have to install the Windows French ISO, adding a language pack doesn't reproduce. And also weirdly.. if you install the French ISO and then add an english language pack it also fails to reproduce.

**Comment by danieljoos** [comment] 2020-05-13 20:43
Merged the changes and created a new version. Thanks again for posting this issue.

**Closed** 2020-05-13 20:42 UTC
